server:
  port: 8081

security:
  oauth2:
    client:
      client-id: exam
      client-secret: exam
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
      id: exam-resource
#      jwt

#spring:
#  redis:
#    port: 6379
#    host: localhost